### PR TITLE
Make actions dumb aware

### PR DESCRIPTION
**Pull request by dima74**
Changes superclass of actions from `AnAction` to `DumbAwareAction`

### CODE REVIEW

**Comment by dima74** [comment]
@mikinw could you please take a look?

**Comment by mikinw** [comment]
I got some free time from work, so I'll have time to look at it in the coming few weeks. Please stay tuned.

**Comment by dima74** [comment]
@mikinw what do you think about using gradle as build system? I can remove it if needed (then pull request will become very small, only 14 changed lines)

**Comment by dima74** [comment]
@mikinw ping

**Review by mikinw — APPROVED** [review]

**Review by mikinw — APPROVED** [review]

**Review by mikinw — APPROVED** [review]

**Comment by mikinw** [comment]
Thanks for the changes. I also removed some garbage and deprecated api usage. Though I had to increase the minimum intellij version

**Pull request merged**
